.TH DOBUTSU 6 "2016-02-08" "Robert Clausecker" "Games"
.
.SH NAME
\fBdobutsu\fR \(en play D\(^obutsu Sh\(^ogi
.
.SH SYNOPSIS
\fBdobutsu\fR
[-\fBqv\fR]
[-\fBc \fIcolor\fR]
[-\fBs \fIstrength\fR[\fI,strength\fR]]
[-\fBt \fItbfile.tb\fR]
.
.SH DESCRIPTION
\fBdobutsu\fR is an engine for the Japanese Sh\(^ogi variant
\fID\(^obutsu Sh\(^ogi\fR with a
.BR gnuchess (6)
like interface. It uses a comprehensive endgame tablebase to
achieve perfect play but can also play at any desired strength.

The following options are supported:
.TP
-\fBc\fR \fIcolor\fR
Make the engine play \fIcolor\fR.  If \fIcolor\fR is one of \fBbBsS\fR,
the engine plays Sente.  If it is one of \fBwWgG\fR, the engine plays
Gote.  More than one colour can be provided to have the engine play
against itself.
.TP
-\fBq\fR
Do not print the board after each move.  This is the default.
.TP
-\fBs \fIstrength\fR[\fI,strength\fR]
Set engine strength to \fIstrength\fR, a positive floating point number.
All values over 700 cause the engine to play perfectly.  If two strength
values of the form \fIstrength,strength\fR are provided, the first
strength is used for Sente while the second strength is used for Gote.
.TP
-\fBt\fR \fItbfile.tb\fR
Load the endgame tablebase from \fItbfile.tb.\fR  If no -\fBt\fR option
is provided, the endgame tablebase is loaded from the location indicated
in the environment variable DOBUTSU_TABLEBASE.  If that variable is
unset, files \fIdobutsu.tb\fR and \fIdobutsu.tb.xz\fR are tried in the
current working directory.
.TP
-\fBv\fR
Print the board after each move.
.
.SH COMMANDS
\fBdobutsu\fR is an interactive program that asks the user for commands
and responds to them if requested.  All interaction, including error
messages, happens on standard input and standard output.  Only error
messages during initialization are printed to standard error.  A command
is either a move in algebraic notation or one of the following:
.TP
\fBboth\fR
Make engine play both players, immediately playing out the rest of the
game at current engine strengths.
.TP
\fBexit\fR
Exit the program.
.TP
\fBforce\fR
Set the engine to play neither Sente nor Gote.
.TP
\fBgo\fR
Make the engine play the colour that is currently on the move.
.TP
\fBhelp\fR
Print a list of commands.
.TP
\fBhint\fR
Print what the engine would play.
.TP
\fBnew\fR [\fIposition\fR]
Start a new game.  If \fIposition\fR is provided, use the specified
position as the starting position, otherwise use the default position.
.TP
\fBremove\fR
Undo the last two moves.
.TP
\fBsetup\fR [\fIposition\fR]
Alias for \fBnew\fR.
.TP
\fBshow \fIthing\fR
Print various useful pieces of information.  Valid values for
\fIthing\fR are:
.RS
.TP
\fBboard\fR
Print the current board.
.TP
\fBmoves\fR
Print all possible moves.
.TP
\fBeval\fR
Print position evaluation.
.TP
\fBlines\fR
Print all possible moves and their evaluation.
.RE
.TP
\fBstrength \fIstrength\fR [\fIstrength\fR]
Set engine strength to a positive floating-point number.  If two
strengths are provided, the first one is used for Sente while the second
one is used for Gote. A strength above 700 makes the engine play
perfectly.
.TP
\fBundo\fR
Undo the previous move.  If the last move was an engine move, the engine
is going to play another move immediately.  Either use \fBforce\fR to
stop the engine or use \fBremove\fR to undo two moves at a time.
.TP
\fBquiet\fR
Do not print the board after every move.
.TP
\fBquit\fR
Quit the program.
.TP
\fBverbose\fR
Print the board after every move.
.TP
\fBversion\fR
Print program version.
.SH ENVIRONMENT
.TP
DOBUTSU_TABLEBASE
The location of the endgame tablebase if no -\fBt \fItbfile.tb\fR option
is specified.
.
.SH FILES
.TP
\fIdobutsu.tb, dobutsu.tb.xz\fR
Endgame tablebase files.  If no -\fBt \fItbfile.tb\fR option is
specified and DOBUTSU_TABLEBASE is unset,
.BR dobutsu (6)
tries to open files named \fIdobutsu.tb\fR and \fIdobutsu.tb.xz\fR in
the current working directory.
.
.SH EXIT STATUS
.TP
1
A fatal error occured.
.TP
0
No fatal error occured.
.
.SH EXAMPLES
.
.SH DIAGNOSTICS
.
.SH SEE ALSO
.BR gnuchess (6),
.BR gnugo (6),
.BR xboard (6)
.
.SH CAVEATS
Even though its user interface is very similar to
.BR gnuchess (6),
.BR dobutsu (6)
is not
.BR xboard (6)
compatible.

Stricly speaking, the D\(^obutsu Sh\(^ogi rules allow either play to
move his Lion to an attacked square on the fourth rank without winning.
The lion can then immediately be captured by the opponent.  As the rules
are not clear as to what happens when the opponent does not immediately
capture, this implementation does not allow the lion to move onto an
attacked square on the fourth rank.  Moving into check is allowed in
other situations.

The -\fBs \fIstrength\fR option adjusts a weighting function used during
move selection.  As the only information the engine has about the
position's evaluation is the entry in the endgame tablebase, its notion
of what is a good move sometimes differs from what a human thinks.
.
.SH HISTORY
D\(^obutsu Sh\(^ogi is a Sh\(^ogi variant invented by professional
Sh\(^ogi player Madoka Kitao in 2008 and solved by University of Tokyo
researcher Tanaka Tetsur\(^o in 2009.  Development of this software
began as a hobby project from the author in July 2016 and concluded in
February 2017.
.
.SH AUTHOR
.UR mailto:fuzxxl@gmail.com
Robert Clausecker <fuzxxl@gmail.com>
.UE
.br
Handjerystra\(sse 26
.br
12489 Berlin
.br
GERMANY
