/* fields on the board:
 *
 * B A 9
 * 8 7 6
 * 5 4 3
 * 2 1 0
 *
 * everything else means piece is on hand.
 */

/* an encoded game position */
typedef unsigned pos_code;
typedef unsigned short board;

#define MAX_POS (pos_code)(256 * 24 * 56 * 56 * 56U)

/* an unpacked game position */
struct position {
	unsigned char l, L, c, C, e, E, g, G;
	unsigned char op;
};

/* for struct position.op */
enum {
	co = 1 << 0,	/* owner 1st chick */
	Co = 1 << 1,	/* owner 2nd chick */
	cp = 1 << 2,	/* promotion 1st chick */
	Cp = 1 << 3,	/* promotion 2nd chick */
	eo = 1 << 4,	/* owner 1st elephant */
	Eo = 1 << 5,	/* owner 2nd elephant */
	go = 1 << 6,	/* owner 1st giraffe */
	Go = 1 << 7	/* owner 2nd giraffe */
};

/*
 * A move description.  piece refers to one of the numbers below.
 * Note that this is always a move for Sente, Gote's moves are never
 * considered as we flip the board between moves.
 */
struct move {
	unsigned char piece, to;
};

/* piece numbers for struct move */
enum {
	PIECE_l, /* can't happen */
	PIECE_L,
	PIECE_c, /* don't care about promotion */
	PIECE_C, /* dito */
	PIECE_e,
	PIECE_E,
	PIECE_g,
	PIECE_G
};

/* from poscode.c */
extern pos_code encode_pos(const struct position*);
extern int decode_pos(struct position*, pos_code);
extern int check_pos(const struct position*);

/* from display.c */
extern int display_pos(const struct position*);
extern int show_pos(const struct position*);

/* from tables.c */
extern const board Rmoves[13], rmoves[13], Llmoves[13], Ggmoves[13], Eemoves[13], Cmoves[13], cmoves[13];

/* from postabs.c, generated by gentabs */
extern const unsigned char lion_decoding[24], pos1_decoding[24 * 11], pos2_decoding[11 * 10 / 2 + 1], flip_op[256];
extern const signed char lion_encoding[7 * 8], pos1_encoding[24 * 13], pos2_encoding[11 * 11];

/* return values for decode_pos and encode_pos */
enum {
	POS_OK      = 0,  /* used internally, not actually returned */
	POS_INVALID = -1, /* invalid position */
	POS_SENTE   = -2, /* gote lion is mated or sente lion is on second row */
};
