/* program to make various tables for poscode.c */

/*
 * The following tables are generated:
 *
 * - op_decoding and op_encoding for conversion between the op byte
 *   and the 90 possible op codes
 * - lion_decoding and lion_encoding to encode the possible lion
 *   positions.
 * - pos_decoding and pos_encoding to convert piece positions between
 *   coordinates and lion-excluding coordinates
 *
 * In the encoding tables, entries that do not have an encoding are
 * marked by being set to -1.
 */

#include <assert.h>
#include <stdio.h>
#include <string.h>

#include "dobutsu.h"

/*
 * Decoding table for the ownership and promotion bits of chicks.
 */
static const unsigned char chick_decoding[10] = {
	0x0, 0x1, 0x3, 0x4, 0x5, 0x7, 0x9, 0xc, 0xd, 0xf
};

/*
 * Decoding table for the ownership bits of other pieces.  The first
 * one is 0 so we can easily find out if both pieces are owned by the
 * same party.
 */
static const unsigned char owner_decoding[3] = {
	0, 1, 3
};

/*
 * Encoding table for the ownership bits of other pieces.
 * The combination 10 is illegal and marked with -1.
 */
static const signed char owner_encoding[4] = {
	0, 1, -1, 2
};

/*
 * Encoding table for the ownership and promotion bits of chicks.
 * Invalid entries are marked -1.
 */
static const signed char chick_encoding[16] = {
	0, 1, -1, 2, 3, 4, -1, 5, -1, 6, -1, -1, 7, 8, -1, 9
};

/*
 * Decoding table for the Lion's positions.  First nibble is
 * sente lion, second nibble is gote lion.
 */
static const unsigned char lion_decoding[21] = {
	0x0b, 0x0a, 0x09, 0x08, 0x07, 0x06, 0x05,
	0x1b, 0x1a, 0x19, 0x18, 0x17, 0x16,
	0x3b, 0x3a, 0x39, 0x36, 0x35,
	0x4b, 0x4a, 0x49
};

/*
 * encoding table for the Lion's positions.  The index has the
 * form (L * 7 + l - 5) where L <= 4 and 5 <= l.
 * Invalid entries are marked -1.
 */
static const signed char lion_encoding[35] = {
	 6,  5,  4,  3,  2,  1,  0,
	-1, 12, 11, 10,  9,  8,  7,
	-1, -1, -1, -1, -1, -1, -1,
	17, -1, -1, 16, 15, 14, 13,
	-1, -1, -1, -1, 20, 19, 18
};

extern int main()
{
	unsigned i, L, l;
	unsigned char lion_decoding[24], op_decoding[90];
	char lion_encoding[56];

	printf("/*\n * Tables for poscode.c generated by gentabs.\n");
	printf(" * This is a generated file, do not edit.\n");
	printf(" * See gentabs.c for documentation.\n */\n\n");

	/* generate decoding table for the owner and promotion fields */
	for (i = 0; i < 90; i++) {
		unsigned Ggo, Eeo, Ccpo, j = i;

		Ccpo = j % 10;
		j /= 10;
		Eeo = j % 3;
		j /= 3;
		Ggo = j;

		op_decoding[i] = chick_decoding[Ccpo] * co
		    | owner_decoding[Eeo] * eo | owner_decoding[Ggo] * go;
	}

	/* decoding table for the owner and promotion fields */
	printf("static const unsigned char op_decoding[90] = {\n");

	for (i = 0; i < 90; i++) {
		printf("%s%#4x,%s", i % 10 == 0 ? "\t" : " ",
		    op_decoding[i], i % 10 == 9 ? "\n" : "");
	}

	printf("};\n\n");

	/* encoding table for the owner and promotion fields */
	printf("static const signed char op_encoding[256] = {\n");
	for (i = 0; i < 256; i++) {
		int encode;

		if ((i & 0xc0) == 0x80 || (i & 0x30) == 0x20 || chick_encoding[i & 0xf] == -1)
			encode = -1;
		else
			encode = chick_encoding[i & 0xf] + 10 * (owner_encoding[i >> 4 & 0x3] + 3 * owner_encoding[i >> 6 & 3]);

		printf("%s%2d,%s", i % 16 == 0 ? "\t" : " ", encode, i % 16 == 15 ? "\n" : "");
	}

	printf("};\n\n");

	/*
	 * lookup table for invariant checks: If bit 0 is set, then the
	 * second chick may not have a higher field number than the
	 * first chick. Bit 1 is for the elephants, bit 2 for the
	 * giraffes.
	 */
	printf("static const unsigned char invariants[90] = {\n");
	for (i = 0; i < 90; i++) {
		unsigned char op = op_decoding[i], check = 0;

		if ((op & (co | Co)) != co &&
		    ((op & (cp | Cp)) == 0 || (op & (cp | Cp)) == (cp | Cp)))
			check |= CINVARIANT;

		if ((op & (go | Go)) != go)
			check |= GINVARIANT;

		if ((op & (eo | Eo)) != eo)
			check |= EINVARIANT;

		printf("%s%d,%s", i % 10 == 0 ? "\t" : " ", check, i % 10 == 9 ? "\n" : "");
	}

	printf("};\n\n");

	/* generate lion_decoding */
	i = 0;
	for (L = 0; L <= 6; L++) {
		/* fields the sente Lion cannot be on */
		if (!(00133 & 1 << L))
			continue;

		for (l = 5; l <= 11; l++) {
			/* if gote lion is in check, the position is invalid */
			if (L == l || Llmoves[L] & 1 << l)
				continue;

			lion_decoding[i++] = L << 4 | l;
		}
	}

	assert(i == 24); /* make sure I got the count right */

	/*
	 * decoding table for the lion's positions. First nibble is the
	 * sente lion's field number, gote is the gote lion's field.
	 */
	printf("static const unsigned char lion_decoding[24] = {\n");
	for (i = 0; i < 24; i++)
		printf("%s%#04x,%s", i % 8 == 0 ? "\t" : " ", lion_decoding[i], i % 8 == 7 ? "\n" : "");
	printf("};\n\n");

	/* generate lion_encoding */
	memset(lion_encoding, -1, sizeof lion_encoding);
	for (i = 0; i < 24; i++) {
		L = lion_decoding[i] >> 4;
		l = lion_decoding[i] & 0xf;

		lion_encoding[8 * L + l - 5] = i;
	}

	/*
	 * encoding table for the lion's positions. The index has the
	 * form 8 * L + (l - 5) where 0 <= L <= 7 and 5 <= l <= 11. A
	 * factor of 7 would have been sufficient, but 8 is faster to
	 * compute and only wastes seven bytes of RAM.
	 */
	printf("static const unsigned char lion_encoding[7 * 8] = {\n");
	for (i = 0; i < 7 * 8; i++)
		printf("%s%2d,%s", i % 8 == 0 ? "\t" : " ", lion_encoding[i], i % 8== 7 ? "\n" : "");

	printf("};\n\n");

	printf("static const unsigned char pos_decoding[24 * 11] = {\n");
	for (i = 0; i < 24 * 11; i++) {
		unsigned Ll = i / 11, pos = i % 11, L, l;

		L = lion_decoding[Ll] >> 4;
		l = lion_decoding[Ll] & 0xf;

		printf("%s%2u,%s", i % 11 == 0 ? "\t" : " ", pos + (pos >= L) + (pos >= l - 1), i % 11 == 10 ? "\n" : "");
	}

	printf("};\n\n");

	printf("static const signed char pos_encoding[24 * 13] = {\n");
	for (i = 0; i < 24 * 13; i++) {
		unsigned Ll = i / 13, pos = i % 13, L, l;
		int encode;

		L = lion_decoding[Ll] >> 4;
		l = lion_decoding[Ll] & 0xf;

		if (pos == L || pos == l)
			encode = -1;
		else
			encode = pos - (pos > L) - (pos > l);

		printf("%s%2d,%s", i % 13 == 0 ? "\t" : " ", encode, i % 13 == 12 ? "\n" : "");
	}

	printf("};\n");

	return (0);
}
